Som devel 20
sorgom/DSTW pull request #44
Opened 2024-02-09 19:28 UTC by sorgom

2024-02-09 20:00 UTC, sombeam requested changes

2024-02-09 20:00 UTC, sombeam commented on specification/ifs/ComTypes.h
>  constexpr auto NumComNameChars = 9;
ComNameSize?

2024-02-09 20:00 UTC, sombeam commented on specification/ifs/ComTypes.h
> +constexpr auto SU8 = sizeof(UINT8);
To avoid endianess issues this mut be 1.
So we don't need a constexpr here.

2024-02-09 20:00 UTC, sombeam commented on specification/ifs/I_SIG_Hub.h
> +    virtual void toFld(size_t id, UINT8 state, UINT8 speed) const = 0;
since speed is only partially an issue - could we have a default 0 here?
virtual void toFld(size_t id, UINT8 state, UINT8 speed = 0) const = 0;

2024-02-09 20:00 UTC, sombeam commented on specification/ifs/I_SIG_Hub.h
> +    virtual void toGui(size_t id, UINT8 state, UINT8 speed) const = 0;
same as above.

2024-02-09 20:00 UTC, sombeam commented on specification/ifs/I_LCR_Hub.h
> +    virtual void toGui(size_t id, UINT8 state, UINT8 ubk) const = 0;
can we make this default with LCR_UBK_STATE_UNDEF?
virtual void toGui(size_t id, UINT8 state, UINT8 ubk = LCR_UBK_STATE_UNDEF) const = 0;

2024-02-09 20:00 UTC, sombeam commented on specification/ifs/SystemEnums.h
> +enum E_Subsys : UINT8
the common order is: TSW, SIG, LCR, SEG

2024-02-09 20:00 UTC, sombeam commented on specification/ifs/SystemEnums.h
> +enum E_Mod : UINT8
check if order is TSW, SIG, LCR, SEG

2024-02-09 20:02 UTC, sorgom commented on specification/ifs/ComTypes.h
>  constexpr auto NumComNameChars = 9;
OK

2024-02-09 20:25 UTC, sorgom commented on specification/ifs/ComTypes.h
> +constexpr auto SU8 = sizeof(UINT8);
ok, replaced.

2024-02-10 13:09 UTC, sorgom commented on specification/ifs/I_SIG_Hub.h
> +    virtual void toFld(size_t id, UINT8 state, UINT8 speed) const = 0;
ok, added defaults

2024-02-10 13:09 UTC, sorgom commented on specification/ifs/I_SIG_Hub.h
> +    virtual void toGui(size_t id, UINT8 state, UINT8 speed) const = 0;
ok, added defaults

2024-02-10 13:13 UTC, sorgom commented on specification/ifs/I_LCR_Hub.h
> +    virtual void toGui(size_t id, UINT8 state, UINT8 ubk) const = 0;
ok, added defaults

2024-02-10 13:56 UTC, sorgom commented on specification/ifs/SystemEnums.h
> +enum E_Subsys : UINT8
ok, changed order

2024-02-10 13:56 UTC, sorgom commented on specification/ifs/SystemEnums.h
> +enum E_Mod : UINT8
ok, and added SUBSYS_SYS

2024-02-10 14:22 UTC, sombeam approved these changes

2024-02-10 14:22 UTC, merged