Som devel 20 refac
sorgom/DSTW pull request #56
Opened 2024-04-18 18:08 UTC by sorgom

2024-04-19 21:25 UTC, sombeam requested changes

2024-04-19 21:25 UTC, sombeam commented on application/components/BAS/BAS_Provider.h
> +//    an I_Provider derived interface
a interface

2024-04-19 21:25 UTC, sombeam commented on application/components/BAS/BAS_Provider.h
> +//  - except the load method which is too specific
it's not the load method, it's the add and comp method

2024-04-19 21:25 UTC, sombeam commented on application/components/BAS/BAS_Provider.h
> +    virtual bool add(size_t id, const ProjItem& item) = 0;
comment methods

2024-04-19 21:25 UTC, sombeam commented on specification/ifs/DataTypes.h
> +struct ComData
maybe add a constructor with PARAM_UNDEF as default

2024-04-19 21:25 UTC, sombeam commented on application/components/SIG/SIG_X.h
> +    inline void toFld(UINT8 state, UINT8 speed = PARAM_UNDEF)
inline is not gcov testable

2024-04-19 21:25 UTC, sombeam commented on application/components/SYS/src/Dispatcher.cpp
> +        const ComTele tele { mIndx.at(id).name, data };
could be done without telegram object

2024-04-19 21:25 UTC, sombeam commented on application/components/SYS/src/Dispatcher.cpp
> +        const ComTele tele { mIndx.at(id).name, data };
could be done without telegram object

2024-04-19 21:25 UTC, sombeam commented on application/components/SYS/src/Reader.cpp
> +            const stype sTSW = nTSW * sizeof(ProjItem);
maybe make a const expr of the size

2024-04-19 21:25 UTC, sombeam commented on application/components/SYS/src/Reader.cpp
>                  is.read(buf, sTSW);
maybe comment that read 0 doesn't do any harm

2024-04-19 21:25 UTC, sombeam commented on devel/TODO.md
maybe remove the whole file: use issues

2024-04-19 21:25 UTC, sombeam commented on make/build.sh
> +for fn in lib_*.make; do
just to remember: could we build some more libs here? e.g. coverage application

2024-04-19 21:25 UTC, sombeam commented on make/premake5_vs.lua
maybe add system tests

2024-04-19 21:25 UTC, sombeam commented on scripts/genCode.py
remove the whole genCode stuff

2024-04-19 21:25 UTC, sombeam commented on scripts/modScanCode.py
remove the code gen stuff

2024-04-19 21:25 UTC, sombeam commented on scripts/modTransTable.py
> +            param1 = 'CMD(_VAL_, 0, _VAL_, 0, _TRG_, 0);',
hm, why is that param1 an not cmd1

2024-04-19 21:25 UTC, sombeam commented on specification/ifs/I_Provider.h
in general: describe the methods

2024-04-19 21:25 UTC, sombeam commented on specification/ifs/values.h
> +enum E_SigType : UINT8
maybe spend a common types enum instead

2024-04-19 21:25 UTC, sombeam commented on testing/testenv/comparators/ostreams.h
> +OSTREAM_DEC(ProjItem)
is that defined and used?

2024-04-19 21:25 UTC, sombeam commented on testing/testenv/comparators/src/installComparators.cpp
>          //# ADD_COMP
remove the gen code tags generally

2024-04-19 21:25 UTC, sombeam commented on testing/testenv/mocks/M_Elem.h
> +
remove empty lines

2024-04-19 21:25 UTC, sombeam commented on testing/testenv/mocks/M_Instances.h
> -    //# MOCK_DEC
remove gen code tags

2024-04-19 21:25 UTC, sombeam commented on testing/testenv/mocks/src/mock_IL.cpp
> +#include <BAS/coding.h>
what for?

2024-04-19 21:25 UTC, sombeam commented on testing/tests/devtests/DT_01.cpp
make clear what this is for or remove

2024-04-19 21:25 UTC, sombeam commented on testing/tests/moduletests/SYS/SYS_01.cpp
>          void expectFail()
is this used?

2024-04-19 21:31 UTC, sorgom commented on application/components/BAS/BAS_Provider.h
> +//    an I_Provider derived interface
an I_Provider...

2024-04-19 21:39 UTC, sorgom commented on testing/testenv/mocks/M_Instances.h
> -    //# MOCK_DEC
this was already removed

2024-04-19 21:41 UTC, sorgom commented on testing/tests/moduletests/SYS/SYS_01.cpp
>          void expectFail()
yes twice

2024-04-20 11:59 UTC, sorgom commented on testing/tests/devtests/DT_01.cpp
we'll leave that for now

2024-04-20 12:44 UTC, sorgom commented on specification/ifs/DataTypes.h
> +struct ComData
added default to members, seems to work

2024-04-20 13:48 UTC, sombeam approved these changes

2024-04-20 13:49 UTC, merged